### ISSUE TITLE
Change text color for increasing contrast ratio

### ISSUE THREAD

**Issue by artemijdeleto** [CINNAMONBUNN/charged#1]
It's almost impossible to read the text entered in search box, especially when use monitor with low brightness. It can be easily fixed by adjusting `color` property in your CSS.

![Search box](https://user-images.githubusercontent.com/24610053/68621956-70d3ab80-04ea-11ea-9c0c-3037371226e9.png)

**Comment by CINNAMONBUNN** [comment]
Ok, I fixed this bug.
